### ISSUE TITLE
About glossary management

### ISSUE THREAD

**Issue by himeyon** [DeepLcom/deepl-java#1]
There seems to be no implementation of glossary management, is there any plan to implement it in the future?
Or is it possible to make a contribution?

[openapi](https://github.com/DeepLcom/openapi) has it.

**Comment by doompadee** [comment]
The readme says:

> "we intend to add support for glossary management soon"

And:
> "We welcome Pull Requests, please read the [contributing guidelines](https://github.com/DeepLcom/deepl-java/blob/main/CONTRIBUTING.md)"

**Comment by himeyon** [comment]
I'm sorry.
Thanks for the comment.

**Comment by daniel-jones-deepl** [comment]
Hi @himeyon, sorry that I didn't reply earlier.

Yes we do intend to add support for glossary management, you're welcome to work on it and submit a Pull Request.

**Comment by daniel-jones-deepl** [comment]
One more thing I wanted to add: if you do want to submit a PR for this, please look at our [.NET client library](https://github.com/DeepLcom/deepl-dotnet) implementation - it would be ideal for us if the client libraries kept a similar design. Thank you 😄

**Comment by daniel-jones-deepl** [comment]
Support for glossary management is added in [v1.0.0](https://github.com/DeepLcom/deepl-java/releases/tag/v1.0.0), any feedback is welcome 😄
