### ISSUE TITLE
deepl-java-0.2.1 and gson

### ISSUE THREAD

**Issue by tig12** [DeepLcom/deepl-java#2]
Hello,
Thanks for the 0.2.1 version.
I'm integrating your library 0.2.1 in a maven project and here is what I notice :
- the <dependency> you cite in the README works but does not automatically include a dependency to gson, which needs to be included by hand with another <dependency>.
- deepl-java-0.2.1 doesn't work with last version of gson (2.9.1). I make it work with gson 2.8.5, already used by deepl-java-0.2.0
Thierry

**Comment by daniel-jones-deepl** [comment]
Hi @tig12, thank you for reporting this, I'll look into it.

**Comment by JanEbbing** [comment]
Hi @tig12 , I could not reproduce this issue (I could build an example project with gson 2.9.1 and deepl-java-0.2.1 (as well as 0.2.0 and 1.0.1). If you still encounter this issue could you please share your `pom.xml` file with your dependencies (ideally a minimal example)?

I also added an [example project](https://github.com/DeepLcom/deepl-java/tree/main/examples/maven/deepl-test-app) using maven in the latest commit.

**Comment by seekuehe** [comment]
Please comment here again if you still need assistance with this issue.
