### ISSUE TITLE
zip END header not found

### ISSUE THREAD

**Issue by msche** [DeepLcom/deepl-java#58]
I just added the maven dependency to my project and see the following fault message appearing:

```
[WARNING] Checksum validation failed, expected '<!doctype' (REMOTE_EXTERNAL) but is actually 'ed96ce2c8f2426c00f632765531cfbd9eec70965' from datapith for https://repsy.io/mvn/datapith/public/com/deepl/api/deepl-java/1.7.0/deepl-java-1.7.0.pom
```

I experienced this for both 1.7.0 and 1.6.0.

**Comment by JanEbbing** [comment]
Hi, which command do you run to see this error message?

When I create a new project with 
```
$ mvn archetype:generate -DgroupId=com.mycompany.app -DartifactId=my-app -DarchetypeArtifactId=maven-archetype-quickstart -DarchetypeVersion=1.5 -DinteractiveMode=false
$ cd my-app
```

Then add the following to my `pom.xml`
```
<dependency>
  <groupId>com.deepl.api</groupId>
  <artifactId>deepl-java</artifactId>
  <version>1.7.0</version>
</dependency>
```

and run `mvn package` I can see in the logs that it downloads `deepl-java` (`Downloaded from central: https://repo.maven.apache.org/maven2/com/deepl/api/deepl-java/1.7.0/deepl-java-1.7.0.jar (55 kB at 374 kB/s)`), but I can't see any errors.

**Comment by msche** [comment]
It seems to be a problem at my side. The DeepL library was picked up from another repository (internal) which had a corrupted file. Corrected it internally and now it seems to work
