### ISSUE TITLE
[Question] Structured document translate

### ISSUE THREAD

**Issue by emartynov** [DeepLcom/deepl-java#6]
It is probably nothing to the java library but a general DeepL translation question.

At the weekend, I tried to translate a bunch of strings and composed one big text to make fewer requests. The format of the string was:
```
<hash of the string to translate>######<text to tranlsate>^^^^^^^
......
```
That worked for some strings. However, DeepL returned a different integer for some hashes or even appended some strings.
That, of course, broke the whole algorithm.

What do you think about how to handle such a translation? Would DeepL ignore an integer from translation if it is part of XML, for example
```
<tr hash="!hash of string to translate!">!string for the translation!</tr>
...
```

Do you have any recommendations or thoughts?

**Comment by JanEbbing** [comment]
Hi @emartynov , yes, for this use case I would suggest using XML handling with something like an "id" attribute with the hash, there is an example in the [docs](https://www.deepl.com/docs-api/xml/markup/).
So the sample code should be:

```java
Translator translator = new Translator(authKey);
System.out.println(translator.translateText(
                                                    "<x id='HASH_OF_STR_1'>1st sentence to be translated.</x>\n"
                                                    + "<x id='HASH_OF_STR_2'>2nd sentence to be translated.</x>\n",
                                                    null,
                                                    "de", // Your Target language
                                                    new TextTranslationOptions().setTagHandling('xml')).getText());
```

Let me know if you have any further issues!
