### ISSUE TITLE
Remove unused dependency

### ISSUE THREAD

**Issue by phinner** [DeepLcom/deepl-java#8]
Hello, I've been using this library for a while now, and I noticed that in my shadowed jar, there were assets for the library `org.apache.commons:commons-math3`. Out of curiosity, I checked the source code to see how it is used, but nowhere in the code the library is actually used.
Is it possible to remove it from the dependencies ?

**Comment by phinner** [comment]
Implemented in https://github.com/DeepLcom/deepl-java/commit/cdf68de52c42b039d8263d04898d6203d5dfcc38

**Comment by JanEbbing** [comment]
There has not been a release made with the new code though, so I'd keep this open until that is done.

**Comment by daniel-jones-deepl** [comment]
[v1.4.0](https://github.com/DeepLcom/deepl-java/releases/tag/v1.4.0) is out, it excludes this dependency.
