### ISSUE TITLE
Keep dependencies up to date with Dependabot

### ISSUE THREAD

**Issue by ParanoidUser** [DeepLcom/deepl-java#9]
Ahoy! 👋

As the topic says, use [Dependabot](https://docs.github.com/en/code-security/dependabot) for automation. Some dependencies are 2-3 years out of date. Let me know if you find such PR useful.

**Comment by JanEbbing** [comment]
Hi @ParanoidUser , thanks for your good suggestion! We are looking to do this, feel free to submit a PR for this to e.g. the Java library.

**Comment by ParanoidUser** [comment]
Hey @JanEbbing, The PR is here #10. Let me know if you have any questions.
